# Generated by Django 5.2.1 on 2025-05-17 14:19

import django.utils.timezone
import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[posts.validators.validate_for_restricted_words]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[posts.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[posts.validators.validate_for_restricted_words]),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[posts.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[posts.validators.validate_for_restricted_symbols, posts.validators.validate_for_restricted_words]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, validators=[posts.validators.validate_for_restricted_words]),
        ),
    ]
