# Generated by Django 5.2.1 on 2025-05-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('gray', 'gray'), ('orange', 'orange'), ('yellow', 'yellow'), ('blue', 'blue'), ('cyan', 'cyan'), ('red', 'red'), ('purple', 'purple')], default='gray', max_length=20),
        ),
    ]
